project_name: "Statistiken"
paths:
  data_raw: "data/lichess_db_standard_rated_2025-03.pgn.zst"
  data_players: "data/players.txt"
  data_games: "data/games.pgn"
  data_final: "data/data.csv"
  engine: "external/stockfish/stockfish-windows-x86-64-avx2.exe"
  opening_book: "external/book/book.bin"
target_size: 15000
target_gpp: 10  # gpp - games per player
engine_depth: 10